name: push_notifications_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  firebase_core: 2.13.1
  firebase_messaging: 14.6.2
  flutter:
    sdk: flutter
  flutter_application_id: ^2.0.0-dev
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^15.1.0+1
  go_router: ^10.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_application_id:
  android:
    id: "com.josemartinez.push_notifications_app"
    name: "com.josemartinez.push_notifications_app"
  ios:
    id: "com.josemartinez.push_notifications_app"
    name: "com.josemartinez.push_notifications_app"
